USE DataWarehouseAnalytics

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

-- Explore all coulmns in specific table
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold.dim_customers'

-- Dimesions Exploration
/*Identifying the unique values (or categories) in each dimension.
Recognizing how data might be grouped or segmented, which is useful for later analysis.
We have to use "DISTINCT" keyword along with dimension name such as DISTINCT Country*/

--Explore All countries our customers from
SELECT DISTINCT country FROM gold.dim_customers

--Explore All Catogories "The major Divisions"
SELECT DISTINCT category FROM gold.dim_products
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products -- It give higher level granularity (Ctagories-4, subcategory-36,productname-295)

-- Date Exploration 
/*Identify the earliest and latest dates (boundaries). Understand the scope of data and the timespan(datediff function to find the timespan). We need min/max functions to get the earliest and lates date information. ex:min/max datecoulmn name*/
-- Find the Date of the First and Last order
SELECT MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date FROM gold.fact_sales
-- How many years of Sales are available
SELECT DATEDIFF(year,min(order_date),max(order_date)) As order_years_range from gold.fact_sales

-- Find the youngest and oldest customers
SELECT MIN(birthdate) AS oldest_birthdate,
MAX(birthdate) AS youngest_birthdate FROM gold.dim_customers

-- Measures Exploration 
/*Calculate the key metric of the business (Big Numbers)
- Highest Level of Aggregation | Lowest Level of Details. Combining aggregate functions with measures such as SUM(sales),AVG(sales) */

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold

-- Find the average selling price
SELECT AVG(price) as avergae_selling_price FROM gold.fact_sales

-- Find the total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
-- Find the total number of Products
SELECT COUNT(product_id) AS total_products FROM gold.dim_products

-- Find the total number of Customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers 

SELECT COUNT(customer_id) AS total_customers FROM gold.dim_customers

--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) FROM gold.fact_sales

-- Generate Report that shows all key metrics of the Business 
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity',SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price',AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders',COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_id)FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers 

-- Magnitude analysis 
/*Compare the measure values by categries. It helps us understand the importance of different categories.(Measure By Dimension, ex: Total quantity by category)*/

-- Find the total Customers by Country 
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find the total customers by Gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find the Total products by category 
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category 
SELECT 
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category 
ORDER BY average_cost DESC

-- What is the total revenue generated by each category 
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer 
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- Find the distribution of sold items across countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC

-- Ranking Analysis 
/*Order the values of dimensions by measure. Top N performers | Bottom N Performers. RANK[Dimension] BY aggreagted Measure*/
/* ex: Rank countries by total sales, Top5  products by quantity, Bottom 3 customers by total orders. To solve these we can use either TOP function or RANK, DENSE_RANK,ROW_NUMBER*/

-- Which 5 products generate the highest revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key= p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- Solving the same question using windows functions such as ROW_NUMBER 
SELECT 
*
FROM(
	SELECT
	p.product_name,
	SUM(f.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON f.product_key= p.product_key
	GROUP BY p.product_name)t
WHERE rank_products <=5

-- What are the 5 worst-performing proucts in terms of sales?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key= p.product_key
GROUP BY p.product_name
ORDER BY total_revenue 


- Advanced Analytics project 
-- Change over time analysis 
/*Analyze how a measure evolves over time. Helps track trends and identify seasonality in your data. (Measure By [Date Dimension]) ex: Total Sales by Year, Average cost by month ?*/
--Change over years (A higher-level overview insights that helps with strategic decision making)
SELECT 
YEAR(order_date) AS order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) AS total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date)

-- Change over months (Detailed insights to discover seasonality in your data)
SELECT 
MONTH(order_date) AS order_month,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) AS total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date)

-- Cumulative Analysis 
/* Aggregate the data progressively over time. Helps to understand whether our business is growing or declining.(Cumulative measure By [Date Column] ex: Running total sales by year, moving average of sales by month( to do this type of analysis we use Aggregate window functions)*/

-- Calculate the total sales per month and the running total of sales over time
SELECT
order_date,
total_sales,
SUM(total_sales) OVER (PARTITION BY order_date ORDER BY order_date) AS running_total_sales
FROM(
	SELECT 
	DATETRUNC(month,order_date) AS order_date,
	SUM(sales_amount) AS total_sales
	FROM gold.fact_sales
	WHERE order_date IS NOT NULL
	GROUP BY DATETRUNC(month,order_date) 
	)t


